print("hello everyone")
print("happy morning")
print("whats the new thing")
print("whats new todat")
print("shalini created the code and updated")
print("shalini edited the navya line")
print("shalini edited ")